package com.greencross.lims.report.panel.enus;

import com.gcgenome.lims.test.panel.TestInfo;
import com.greencross.lims.report.builder.LogoType;
import lombok.Getter;
import lombok.experimental.Accessors;

@Getter
@Accessors(fluent = true)
public class HereditaryTemplateEnUsON040 extends HereditaryTemplateEnUs {
	private final HereditaryResourceEnUsON040 resource;
	public HereditaryTemplateEnUsON040(HereditaryResourceEnUsON040 resource, TestInfo testInfo, LogoType logoType) {
		super(testInfo, logoType);
		this.resource = resource;
	}
	private final String lblCategory = "";
	private final String lblTitle = testInfo().name();
	@Override
	public HereditaryResourceEnUs resource() {
		return resource;
	}

	@Override
	CancerType[] cancerTypes() {
		return CancerTypeN040.values();
	}
	@Getter
	@Accessors(fluent = true)
	private enum CancerTypeN040 implements CancerType {
		BREAST("Breast","Breast cancer is a malignant tumor that may spread beyond the breast and threaten a patient’s life. Any cells of the breast may become cancer. In general, breast cancer may initially cause no symptoms. The most common symptom is a painless fixed lump in a breast or breast enlargement. 50% of breast cancer cases are located in the exterior part of the upper breast. Females can check their breasts through breast self-examination. Over 70% of patients with breast cancer discover their condition through a self-examination. The best time to examine your breasts is 1 week after the end of your menstrual period when your breasts are tender. If you had a hysterectomy or are in menopause, breast self-examination is recommended every month.",
				"Hereditary breast cancers are usually autosomal dominant and associated with pathogenic variants of the BRCA1 and BRCA2 genes. BRCA1 and BRCA2, identified in 1994 and 1995, respectively, are considered to be one of the most important factors for the pathogenesis of breast cancers because the incidence of breast cancer is significantly increased with pathogenic variants of BRCA1 and BRCA2. BRCA1 and BRCA2 are located on the long arm of chromosome 17 and chromosome 13, respectively. In case of DNA damage, these genes, reacting with other proteins, play a role in repairing the damaged double strand DNA. If BRCA1 or BRCA2 is damaged, the DNA repair process is not properly performed, and therefore, the risk of cancer increases. Pathogenic variants of the BRCA genes are autosomal dominantly inherited and the same genetic disorders have a 50% probability of occurring in the patient’s offsprings and other family members. However, not all hereditary breast cancer have BRCA1 or BRCA2 pathogenic variants. Some tumor suppressor genes and DNA repair genes are also associated with increased risk of breast cancer. Pathogenic variants in the ATM, CDH1, CHEK2, NBN, NF1 and PALB2 genes increase breast cancer risk. Depending on the positive genetic results, breast cancer screening through MRI mammography is recommended for those in 30 to 40 years of age. Therefore, when a pathogenic variant is found in a patient, the patient's offsprings and family members in close relationships are recommended to have genetic testing.",
				GeneN040.ATM, GeneN040.BARD1, GeneN040.BRCA1, GeneN040.BRCA2, GeneN040.BRIP1, GeneN040.CDH1, GeneN040.CHEK2, GeneN040.NBN, GeneN040.NF1, GeneN040.PALB2, GeneN040.PPM1D, GeneN040.PTEN, GeneN040.RAD51C, GeneN040.STK11, GeneN040.TP53),
		OVARY("Ovary",
				"Ovarian cancer is a cancer that forms in an ovary. Ovarian cancer is largely divided into epithelial ovarian cancer, germ cell tumor, and sex cord stromal tumor, depending on the tissue where the tumor develops. Epithelial ovarian cancer means cancer started in epithelial cells on the surface of the ovary. Over 90% of malignant tumors of the ovary are epithelial. Common signs and symptoms of epithelial ovarian cancer include stomachache, abdominal distention, abdominal swelling, intra-abdominal lump, abnormal vaginal bleeding, frequent urination, dysuria, abnormal vaginal discharge, nausea, vomiting, constipation, and backache.",
				"Hereditary ovarian cancers are usually autosomal dominant and associated with pathogenic variants of the BRCA1 and BRCA2 genes. BRCA1 and BRCA2, identified in 1994 and 1995, respectively, are considered to be one of the most important factors for the pathogenesis of ovarian cancers because the incidence risk of breast cancer is significantly increased with pathogenic variants of BRCA1 and BRCA2. BRCA1 and BRCA2 are located on the long arm of chromosome 17 and chromosome 13, respectively. In case of DNA damage, these genes, reacting with other proteins, play a role in repairing the damaged double strand DNA. If BRCA1 or BRCA2 is damaged, the DNA repair process is not properly performed, and therefore, the risk of cancer increases. Pathogenic variants of the BRCA genes are autosomal dominantly inherited and the same genetic disorders have a 50% probability of occurring in the patient’s offsprings. However, not all hereditary ovarian cancer have BRCA1 or BRCA2 pathogenic variants. Pathogenic variants in the BRIP1 and RAD51C genes also increase the risk of ovarian cancer. If pathogenic variants are detected in these genes, counseling for prophylactic ovarian resection is required between 45 and 50 years of age based on the family history of ovarian cancer. Therefore, when a pathogenic variant is found in a patient, the patient’s offsprings and family members in close relationships are recommended to have genetic testing.",
				GeneN040.BRCA1, GeneN040.BRCA2, GeneN040.BRIP1, GeneN040.DICER1, GeneN040.EPCAM, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.PALB2, GeneN040.PMS2, GeneN040.PPM1D, GeneN040.RAD51C, GeneN040.RAD51D, GeneN040.STK11, GeneN040.TP53),
		UTERINE("Uterine",
				"The uterus is part of the female reproductive system. It is where a baby grows and develops during pregnancy. There are two main types of cancer in the uterus such as endometrial carcinoma and uterine sarcoma. Endometrial carcinoma commonly starts in the endometrium and is often found before it has spread beyond the uterus. The most common symptom of endometrial carcinoma is abnormal vaginal bleeding. However, uterine sarcoma starts in connective tissue of the uterus. It is rare and hard to treat compared to the endometrial carcinoma.",
				"Hereditary endometrial cancer is strongly related to Lynch syndrome. Lynch syndrome is an inherieted cancer syndrom caused by the pathogenic variant in the MLH1, MSH2 and MSH6 genes, and it is inherited as autosomal dominant manner. In Lynch syndrome, endometrial cancer can be found about 10-20 years earlier. The MLH1 gene is located in the short arm of chromosome 3, and MSH2 and MSH6 genes are located in the short arm of chromosome 2. MLH1, MSH2 and MSH6 genes are involved in the correction of wrong replication of DNA, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated, which makes cancer cells. The other inherieted cancer syndrom, Li-Fraumeni syndrome caused by the pathogenic variant in the TP53 can increase the risk of uterine sarcoma.",
				GeneN040.EPCAM, GeneN040.FH, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.PMS2, GeneN040.PTEN, GeneN040.STK11, GeneN040.TP53),
		PROSTATE("Prostate",
				"Prostate cancer is a medical condition in which the cells of the prostate divide and grow abnormally and consequently become a malignant tumor. The tumor may invade nearby tissues without being confined to the prostate or may spread to other organs through blood vessels or lymphatic vessels. Prostate cancer may initially cause no symptoms. In later stages, patients experience a variety of urinary problems (nocturia, frequent urination, urinary hesitancy, etc.). Symptoms of more advanced prostate cancer include hydronephrosis (the swelling of a kidney due to the blockage of the ureter), renal failure, bone pain due to metastasis (including backache and sciatic neuralgia), and distal femur or spinal fractures.",
				"Hereditary prostate cancer is associated with the pathogenic variants of MLH1, MSH2, MSH6, PMS2, and homologous recombination genes. MLH1, MSH2, MSH6, and PMS2 are associated with Lynch syndrome, the inherited cancer syndrome. The risk of prostate cancer in patients with the pathogenic variants of these genes is about 5-16%. The homologous recombination genes, BRCA1, BRCA2, ATM, PALB2, and CHEK2 are involved in the double-stranded DNA repair process. If there is an abnormality in these gene functions, there is a problem in the DNA repair process, and the risk of cancer increases. If pathogenic variants are detected in these genes, prostate cancer can develop at a relatively early age, under the age of 55, so early screening for prostate cancer is required from the age of 45.",
				GeneN040.ATM, GeneN040.BRCA1, GeneN040.BRCA2, GeneN040.CHEK2, GeneN040.HOXB13, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.NBN, GeneN040.PALB2, GeneN040.PMS2, GeneN040.TP53),
		STOMACH("Stomach",
				"Gastric cancer (stomach cancer) is a malignant tumor that develops in the stomach. Early symptoms may include indigestion, heartburn, upper abdominal pain or discomfort, nausea, weight loss, loss of appetite, and fatigue. In the case of advanced gastric cancer, the patient may experience vomiting because the part between the stomach and the duodenum can be narrow or blocked. Other signs may include hematemesis, melena, abdominal mass, and hepatomegaly. However, many patients with early gastric cancer do not experience any symptoms and find their condition by accident. Therefore, it is important to undergo gastroscopy on a regular basis.",
				"Certain genetic syndrome may increase the risk of gastric cancer. These include Hereditary diffuse gastric cancer and Lynch syndrome. Hereditary diffuse gastric cancer(HDGC) is associated with pathogenic variants in the CDH1 gene and inherited in an autosomal dominant manner. The average age of onset of HDGC is 38 years. Most of the individuals with CDH1 gene pathogenic variant develop cancer before age 40. The estimated cumulative risk of gastric cancer by age 80 years is 70% for men and 56% for women. MLH1, MSH2, and MSH6 genes associated with Lynch syndrome are involved in the repair system of DNA replication error, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated, which becomes cancer. Pathogenic variants of these genes are inherited autosomal dominantly. The risk of gastric cancer in patients with the pathogenic variants of these genes is about 8~16%.",
				GeneN040.APC, GeneN040.BMPR1A, GeneN040.CDH1, GeneN040.EPCAM, GeneN040.KIT, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.PMS2, GeneN040.SMAD4, GeneN040.STK11),
		COLORECTAL("Colorectal",
				"Patients with early-stage colorectal cancer generally do not experience any symptoms. Colorectal cancer can be advanced when symptoms appear. Common signs and symptoms of colorectal cancer are bowel habit change, diarrhea, constipation, rectal tenesmus, blood in the stool, mucous stool, stomachache, abdominal distention, fatigue, loss of appetite, indigestion, and abdominal mass. In the advanced stage, the recurrence rate is increased after surgery compared to the early stage.  Patients should get regular check-ups proactively for 5 years after treatment.",
				"There are several types of hereditary cancer syndromes that increase the risk of colorectal cancer. Lynch syndrome, also known as hereditary non-polyposis colorectal cancer, is caused by a pathogenic variant in the MLH1, MSH2, and MSH6 genes. MLH1, MSH2, and MSH6 genes are involved in the repair system of DNA replication error, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated. It is known that 50% of pathogenic variants associated with Lynch syndrome are found in MLH1 and 40% and 7-10% are found in MSH2 and MSH6, respectively. Pathogenic variants of these genes are autosomal dominantly inherited and have a 50% probability of inheritance in the patient’s offspings. Polyposis syndromes are a group of cancer syndromes that cause multiple colorectal polyps. The APC gene, a tumor suppressor gene is associated with familial adenomatous polyposis (FAP). A pathogenic variant of the APC can induce an overgrowth of cells and generates polyps in the large intestine. If one has a pathogenic variant of the APC gene, the rate of colorectal cancer occurrence is almost 100%. Pathogenic variants of the APC gene are found in 90% of FAP patients. It is inherited in an autosomal dominant manner. Therefore, when a pathogenic variant is found in a patient, the patient’s offspings and family members are recommended to have genetic testing. Other genes that cause polyposis syndrome, are MUTYH, BMPR1A, and SMAD4. These genes are inherited in an autosomal recessive manner.",
				GeneN040.APC, GeneN040.BLM, GeneN040.BMPR1A, GeneN040.CDH1, GeneN040.CHEK2, GeneN040.EPCAM, GeneN040.KIT, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.MUTYH, GeneN040.PMS1, GeneN040.PMS2, GeneN040.PTEN, GeneN040.SMAD4, GeneN040.STK11, GeneN040.TP53),
		LUNG_AND_PLEURA("Lung and Pleura",
				"Lung cancer is divided into non-small cell lung and small cell lung cancer. Small cell lung cancer is known to be more aggressive. In many cases, lung cancer has already spread to other organs or the other lung through lymphatic vessels or blood vessels when the cancer is found. Lung cancer has a high risk of recurrence and metastasis. As a result, there is a high risk of death. Therefore, prevention is the most important. Patients with lung cancer should manage their health constantly even after treatment.",
				"EGFR is one of the well-known genes that increase the risk of lung cancer. EGFR protein functions in the cell growth. The pathogenic variant in the EGFR gene may be associated with dysregulation of cell growth, which can cause cancer. EGFR-positive lung cancer represents about 30-40% in Asia and 10-15% in the United States and Europe and generally appears in the adenocarcinoma subtype of non-small cell lung cancer. The pathogenic variants of the BAP1 and DICER1 genes are also associated with lung cancer.",
				GeneN040.BAP1, GeneN040.DICER1, GeneN040.EGFR),
		SMALL_INTESTINES("Small Intestines",
				"The small intestine is a part of the digestive system, carries digested food between the stomach and the large intestine. Small intestine cancer is a rare type of cancer. Blood in the stool is a common symptom. Sometimes cancer can block the intestine, causing crampy abdominal pain and vomiting. Also, unexplained weight loss can occur.",
				"Certain genetic polyposis syndromes and hereditary cancer syndromes are associated with increased risks for small intestine cancer. These include Peutz-Jeghers syndrome and Lynch syndrome. Peutz-Jeghers syndrome is associated with pathogenic variants in the STK11 gene.This disease is inherited in an autosomal dominant manner. This disease forms gastrointestinal hamartoma and is characterized by pigmentation in the mucous membranes. Gastrointestinal hamartoma is most common in the small intestine (78%), but also occurs in the stomach (38%) and large intestine (20-40%). MLH1, MSH2, and MSH6 genes associated with Lynch syndrome are involved in the repair system of DNA replication error, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated, which becomes cancer. Pathogenic variants of these genes are inherited autosomal dominantly. Individuals with MLH1 or MSH2 pathogenic variants have an increased risk of small intestine cancer.",
				GeneN040.KIT, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.SDHB, GeneN040.SDHC, GeneN040.SDHD, GeneN040.STK11),
		ESOPHAGUS("Esophagus",
				"Esophageal cancer is divided into cervical esophageal cancer, thoracic esophageal cancer, and gastroesophageal junction cancer, depending on the location of the lesion. One of the most common symptom is difficulty in swallowing. In the case of advanced esophageal cancer, patients commonly experience weight loss due to undernutrition. Patients may suffer pain or not.",
				"Certain genetic syndromes increase the risk of esophageal cancer. These include Fanconi anemia and tylosis with esophageal cancer. Fanconi anemia is associated with pathogenic variant of FANCA. The pathogenic variant of RHBDF2  causes tylosis with esophageal cancer. Ile186Thr, Pro189Leu, and Asp188Asn are well known to be related to esophageal cancer.",
				GeneN040.FANCA, GeneN040.FANCB, GeneN040.FANCC, GeneN040.FANCD2, GeneN040.FANCE, GeneN040.FANCF, GeneN040.FANCG, GeneN040.FANCI, GeneN040.FANCL, GeneN040.FANCM, GeneN040.RHBDF2),
		URINARY_TRACT_AND_BLADDER("Urinary Tract and Bladder",
				"Bladder cancer is mostly epithelial tumors arising from epithelial cells. Depending on the progression, bladder cancer is also divided into non-muscular bladder cancer, which is limited to the bladder mucosa or the lower mucous membrane, and myofascial bladder cancer and metastatic bladder cancer in which bladder cancer invaded the muscle layer. One of the most common symptoms of bladder cancer is visually identifiable blood in the urine without pain. Other signs and symptoms include frequent urination, pain with urination, and urinary incontinence. When bladder cancer has been already advanced, patients may experience weight loss and other symptoms in the metastasis site such as bone pain resulting from bone metastasis. Patients with advanced bladder cancer may find a lump in the lower abdomen or have flank pain due to hydronephrosis.",
				"Bladder cancer risk is increased in individuals with Lynch syndrome, hereditary cancer syndrome. MLH1, MSH2, and MSH6 genes associated with lynch syndrome are involved in the repair system of DNA replication error, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated, which becomes cancer. The inheritance of pathogenic variants of these genes is in autosomal dominant manner. The risk of bladder cancers in individuals with an MLH1 or MSH2 pathogenic variant is 1%-4%.",
				GeneN040.HRAS, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6),
		PANCREAS("Pancreas",
				"The pancreas, which is located behind the stomach and connected to the duodenum, secretes digestive enzymes and hormones. Insulin and glucagon, involved in blood sugar control, are also secreted from the pancreas. Tumors mainly develop in exocrine cells. Pancreatic cancer usually has poor prognosis after treatment. The most common symptoms of pancreatic cancer include stomachache, backache and weight loss. It may be accompanied by jaundice or indigestion and diabetes may occur or worsen.",
				"Certain cancer-related genetic syndromes increase the risk for pancreatic cancer. These include Peutz-Jeghers syndrome, Lynch syndrome, and hereditary breast-ovarian cancer syndrome. MLH1, MSH2, and MSH6 genes associated with Lynch syndrome are involved in the repair system of DNA replication error, and when they have a pathogenic variant, errors occurring during DNA replication are accumulated, which becomes cancer. Pathogenic variants of these genes are inherited autosomal dominantly. BRCA1, BRCA2, and other homologous recombination repair genes are also related to pancreatic cancer. If these genes are damaged, the DNA repair process is not properly performed, and therefore, the risk of cancer increases. The pathogenic variant of the CDNKN2A gene that causes familial malignant melanoma syndrome may increase the risk of pancreatic cancer.",
				GeneN040.APC, GeneN040.ATM, GeneN040.BMPR1A, GeneN040.BRCA1, GeneN040.BRCA2, GeneN040.CDK4, GeneN040.CDKN2A, GeneN040.EPCAM, GeneN040.MEN1, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.NF1, GeneN040.PALB2, GeneN040.PMS2, GeneN040.SMAD4, GeneN040.STK11, GeneN040.TP53, GeneN040.VHL),
		KIDNEYS("Kidneys",
				"Kidney cancer is classified into renal pelvic cancer and renal cell cancer, depending on the location of the lesion. In general, kidney cancer refers to renal cell cancer. 85-90% of tumors arising from the kidneys are renal cell cancer. In many cases, kidney cancer does not cause any symptoms. As kidney cancer becomes more advanced or spreads to other organs, it results in flank pain, blood in the urine, and a mass (or a lump) in the flank or the upper abdomen. Only 10-15% of cases experience all these symptoms. Other signs and symptoms include weight loss, fatigue, loss of appetite, and fever.",
				"Certain genetic syndromes increase the risk of kidney cancer. These are called hereditary renal cell carcinoma (HRCC), such as von Hippel-Lindau disease (VHL), hereditary leiomyomatosis and renal cell cancer (HLRCC), Birt-Hogg-Dubé syndrome (BHD), hereditary papillary renal cancer (HPRC). VHL is associated with a pathogenic variant of the VHL gene, which is the tumor suppressor gene. It is inherited in an autosomal dominant manner. HLRCC, BHD, and HPRC are associated with pathogenic variants of the FH gene, FLCN gene, and MET gene, respectively. They are inherited autosomal dominantly.",
				GeneN040.BAP1, GeneN040.BUB1B, GeneN040.CEP57, GeneN040.DICER1, GeneN040.DIS3L2, GeneN040.FH, GeneN040.FLCN, GeneN040.MET, GeneN040.PTEN, GeneN040.SDHB, GeneN040.SDHC, GeneN040.SDHD, GeneN040.SMARCB1, GeneN040.TSC1, GeneN040.TSC2, GeneN040.VHL, GeneN040.WT1),
		CERVIX("Cervix",
				"The cervix is the narrow lower part of the uterus and is connected to the vagina. Cervical cancer accounts for 3.4% of female-specific cancers in 2014. 20% of cervical cancer cases occur in young women in their 20s or 30s. Females should pay attention to this disease at young ages. Signs and symptoms of cervical cancer include vaginal bleeding, an increase in vaginal discharge, pelvic pain, backache, and weight loss.",
				"The hereditary cervical cancer is associated with Peutz-Jeghers Syndrome. Peutz-Jeghers syndrome is caused by pathogenic variants that occur in the STK11 gene. This disease is inherited in an autosomal dominant manner. The risk for cervical cancer with Peutz-Jeghers syndrome is about 10%.",
				GeneN040.STK11),
		SKIN("Skin",
				"Skin cancer often develops on the skin exposed to the sun. The three main types of skin cancer are basal cell carcinoma, melanoma, and squamous cell carcinoma. These three types are associated with, at least in part, long-term sun exposure. Basal cell carcinoma usually occurs in sun-exposed areas of your body, as a pearly or waxy bump. Squamous cell carcinoma occurs on sun-exposed areas of your body as a firm, red nodule. Melanoma can develop anywhere on your body. Its major signs are a large brownish spot with darker speckles and a mole that changes in color, size or feel or that bleeds.",
				"Many genetic factors can increase the risk of developing melanoma and other skin cancers. The major germline tumor suppressor gene associated with melanoma is CDKN2A. The pathogenic variants in CDKN2A have been estimated to account for 35% to 40% of all familial melanomas. Germline pathogenic variants in several other genes, including CDK4, and BAP1 have also been found to be associated with melanoma.",
				GeneN040.BAP1, GeneN040.CDK4, GeneN040.CDKN2A, GeneN040.DDB2, GeneN040.ERCC2, GeneN040.ERCC3, GeneN040.ERCC4, GeneN040.ERCC5, GeneN040.NF2, GeneN040.PTEN, GeneN040.TP53, GeneN040.XPA, GeneN040.XPC),
		BONE("Bone",
				"Bone cancer can begin in any bone in the body, but it most commonly affects the pelvis or the long bones in the arms and legs. In general, benign bone tumor is more common than malignant tumor. There are three major types of bone cancer such as osteosarcoma, Ewing's sarcoma, and chondrosarcoma. Osteosarcoma often forms around your knee and upper arm. Teens and young adults are most likely to get it, but another form of osteosarcoma is common in adults who have Paget's disease of bone. Ewing's sarcoma usually occurs in people between the ages of 5 and 20. The ribs, pelvis, leg, and upper arm are the most common sites of involvement. It can also develop in the soft tissue around your bones. Chondrosarcoma occurs most often in people between ages 40 and 70. The hip, pelvis, leg, arm, and shoulder are common sites of involvement.",
				"Li-Fraumeni syndrome can increase the risk of developing bone cancer. It is caused by the pathogenic variant of the TP53 gene. The TP53 gene is a representative anti-oncogene and is located in the short arm of chromosome 17.  Osteosarcomas account for 3%-16% of LFS cancers and typically occur before the age of 30 years. EXT1 and EXT2 genes form the protein that is an essential factor in a signal transduction cascade for the regulation of chondrocyte differentiation, ossification, and apoptosis. The pathogenic variants of these genes may cause chondrosarcoma.",
				GeneN040.EXT1, GeneN040.EXT2, GeneN040.RECQL4, GeneN040.TP53),
		THYROID_GLAND("Thyroid Gland",
				"The thyroid is a butterfly-shaped endocrine organ located below the thyroid cartilage that protrudes in the front of the neck. The thyroid is involved in metabolism by producing and storing the thyroid hormones that regulate body temperature, metabolism, and growth. Lumps that develop in the thyroid are called thyroid nodules. 5-10% of these nodules are found to be cancerous. Unlike benign nodules, thyroid cancer increases in size and invades the surrounding tissues or may cause lymph node metastases or remote metastasis. In many cases, patients with thyroid cancer do not experience any symptoms. In the case of advanced cancer, the patient may find a mass in the neck and the tumor may invade the nerves of the vocal cords, which causes vocal changes. If the tumor grows larger, the patient may experience difficulty swallowing or shortness of breath.",
				"About 20% of medullary thyroid cancer is hereditary. The cause is a pathogenic variant of the RET gene, and it is inherited in an autosomal dominant manner. If the patient has a pathogenic variant of the RET gene, medullary thyroid cancer occurs in almost 100% of cases. The RET gene is a proto-oncogene located in the long arm of chromosome 10. Also, the pathogenic variant of the MEN1 gene may cause thyroid adenoma. There has been a report that thyroid disease occurs in more than 25% of people who have a MEN1 variant.",
				GeneN040.APC, GeneN040.CHEK2, GeneN040.DICER1, GeneN040.MEN1, GeneN040.PRKAR1A, GeneN040.PTEN, GeneN040.RET, GeneN040.TP53),
		LIVER("Liver",
				"The liver is a significant organ responsible for various metabolic activities including vitamins, minerals, hormones, and detoxification as well as the three major nutrients such as carbohydrate, protein, and fat. A malignant tumor originating in liver cells is called liver cancer. Liver cancer is associated with upper abdominal pain, lump, abdominal distention, weight loss, excessive fatigue, indigestion, etc. However, you must be careful because you may have late onset of symptoms of liver lesion. You can expect good prognosis if treated early. Liver diseases such as hepatitis or cirrhosis increase the risk of recurrence and metastasis to your bones or lungs.",
				"There is some hereditary syndrome related to liver cancer. Familial adenomatous polyposis (FAP) is associated with increased risk of liver cancer, which is cause by pathogenic variants of APC. A pathogenic variant of the APC gene is associated with dysregulation of cell growth. The risk for hepatoblastoma in FAP is 750 to 7500 times higher than in the general population and the lifetime risk is estimated at 1.6%. The majority of hepatoblastomas occur before age three years.",
				GeneN040.APC, GeneN040.HNF1A),
		SOFT_TISSUE("Soft Tissue",
				"Soft tissue sarcomas are a group of rare cancers affecting the tissues that connect, support and surround other body structures and organs. Tissues that can be affected by soft tissue sarcomas include fat, muscle, blood vessels, deep skin tissues, tendons and ligaments. Soft tissue sarcomas can develop in almost any part of the body, including the legs, arms and tummy (abdomen).",
				"The pathogenic variant in the RB1 gene results in the loss of cell proliferation inhibitory function and causes retinoblastoma. Retinoblastoma can be caused by the loss of heterozygosity of the RB1 gene. Patients with retinoblastoma have an increased risk of soft-tissue sarcomas. Also, Werner syndrome patients have an increased risk of soft tissue sarcoma, which is associated with pathogenic variants of WRN.",
				GeneN040.RB1, GeneN040.WRN),
		MISCELLANEOUS_ENDOCRINE_GLANDS("Miscellaneous Endocrine Glands",
				"Miscellaneous endocrine tumors are developed in endocrine glands or in cells that produce hormones. These include adrenal cortical tumors, parathyroidoma, and paraganglioma. Because endocrine tumors come from cells that make hormones, the tumors themselves can begin to make hormones. This upsets the delicate hormonal balance that keeps the body working properly.",
				"Certain hereditary cancer syndromes are associated with increased risks for endocrine tumors. These include multiple endocrine neoplasias and hereditary paraganglioma pheochromocytoma syndrome. Multiple endocrine neoplasia type 1 is a tumor syndrome that develops tumors in parathyroid glands, pancreatic nerve endocrine system, anterior pituitary, and skin. It is associated with a pathogenic variant of the MEN1 gene. Multiple endocrine neoplasia type 1 is inherited in an autosomal dominant manner with the incidence of 2-20 in 100,000 population. Hereditary paraganglioma-pheochromocytoma syndrome is related to the pathogenic variants of SDHD, SDHC, SDHB, and SDHAF2 genes. Although the disease is inherited in an autosomal recessive manner, its expressivity differs according to the gene, age, and location of tumors. Tumors of patients with SDHB pathogenic variants have a high risk of malignant transformation.",
				GeneN040.CDC73, GeneN040.FH, GeneN040.MAX, GeneN040.MEN1, GeneN040.RET, GeneN040.SDHAF2, GeneN040.SDHB, GeneN040.SDHC, GeneN040.SDHD, GeneN040.TMEM127, GeneN040.VHL),
		BLOOD("Blood",
				"Blood cell cancers affect blood cells and bone marrow, the spongy tissue inside your bones where blood cells are made. These cancers change the way blood cells behave and how well they work. There are three major types of blood cell cancer such as leukemia, lymphoma, and myeloma. Leukemia is a cancer of white blood cells or cells that become white blood cells. Lymphoma is a cancer of the lymphatic system, particularly lymph nodes. Myeloma is a cancer of the plasma cells, which are lymphocytes that make antibodies to protect against infections. These cancers cause your bone marrow and lymphatic system to make blood cells that don't work as well as they should. Major symptoms include fever, chills, fatigue, weakness, weight loss, bone, joint pain, and anemia.",
				"There are some germline variants related to blood cancer. 212delC in the CEBPA gene is detected in Acute Myeloid Leukemia patients. Also, the genetic abnormality of GATA2 and RUNX1 is associated with leukemia. The variants of PRF1 are detected in familial lymphoma patients.",
				GeneN040.CEBPA, GeneN040.GATA2, GeneN040.PRF1, GeneN040.RUNX1, GeneN040.SBDS),
		HEAD_AND_NECK("Head and Neck",
				"Head and neck cancer refers to any malignant tumor that develops in the face, nose, neck, oral cavity, larynx, pharynx, salivary glands, and thyroid, except the brain and eyes. Cancer that develops in the oral cavity, the larynx, and the pharynx is called oral cancer, laryngeal cancer, and pharyngeal cancer, respectively. Pharyngeal cancer is classified into nasopharyngeal cancer, oropharyngeal cancer, and hypopharyngeal cancer, depending on the location of the lesion. Thyroid cancer can be included in head and neck cancer. Signs and symptoms vary depending on the location of the lesion. However, common symptoms include voice changes, difficulty swallowing, shortness of breath, and foreign body sensation in the neck, since the relevant organs are involved in speaking, breathing, and swallowing.",
				"Certain genetic syndromes increase the risk of head and neck cancer. These include Fanconi anemia which is caused by the pathogenic variant of FANCA, FANCC, and FANCG. Head and neck squamous cell carcinomas (HNSCCs) are the most common solid tumor in individuals with Fanconi anemia. The incidence is 500 to 700-fold higher than in the general population. Also, HNSCC with Fanconi anemia occurs at an earlier age (20-40 years) than in the general population.",
				GeneN040.CDK4, GeneN040.CYLD, GeneN040.FANCA, GeneN040.FANCB, GeneN040.FANCC, GeneN040.FANCD2, GeneN040.FANCE, GeneN040.FANCF, GeneN040.FANCG, GeneN040.FANCI, GeneN040.FANCL, GeneN040.FANCM, GeneN040.SLX4),
		CENTRAL_NERVOUS_SYSTEM("Central Nervous System",
				"Tumors in the brain and spinal cord are called central nervous system (CNS) tumors. A CNS tumor can be either cancerous or benign, and both types can potentially be dangerous. A CNS tumor is especially problematic because a person’s thought processes and movements may be affected and, the tissues around the tumor are often vital to the body’s functioning. Symptoms are not the same for everyone. They depend on where a tumor is and how large it is.",
				"Several genetic tumor syndromes have been associated central nervous system (CNS) tumors. These include Li-Fraumeni syndrome, neurofibromatosis, and Turcot syndrome. Li-Fraumeni syndrome is caused by pathogenic variants of the TP53 gene. Central nervous system tumors account for 9%-14% of Li-Fraumeni syndrome cancers. Neurofibromatosis is associated with the NF1 or NF2 genesurcot syndrome is a historical term used to describe individuals presenting with colorectal cancer or one or more colorectal adenomas in addition to tumors of the central nervous system. Pathogenic variants in the APC, MLH1, MSH2, MSH6, and PMS2 may increase the risk of CNS tumors.",
				GeneN040.AIP, GeneN040.APC, GeneN040.CDKN1C, GeneN040.CDKN2A, GeneN040.DICER1, GeneN040.GPC3, GeneN040.MLH1, GeneN040.MSH2, GeneN040.MSH6, GeneN040.NBN, GeneN040.NF2, GeneN040.PMS2, GeneN040.PRKAR1A,
				GeneN040.PTCH1, GeneN040.PTEN, GeneN040.SMARCA4, GeneN040.SMARCB1, GeneN040.SUFU, GeneN040.TP53, GeneN040.TSC2),
		PERIPHERAL_NERVOUS_SYSTEM("Peripheral Nervous System",
				"Peripheral nerve tumors are growths in or near the strands of tissue (nerves) that transmit signals from your brain. Peripheral nerve tumors can occur anywhere in the body. The major symptoms of peripheral nerve tumors develop from direct effects on the main nerve or from the tumor pressing on nearby nerves, blood vessels, or tissues. The symptoms vary depending on the location of the tumors. They include swelling or a lump under the skin, pain, tingling, or numbness.",
				"Neurofibromatosis type 1 is the most frequent of the inherited genetic syndromes resulting in peripheral nerve tumors. Neurofibromatosis type 1 is caused by the pathogenic variants of the NF1 gene. NF1 is inherited in an autosomal dominant manner. Also, neurofibromatosis type II is well known hereditary peripheral nerve tumor. Neurofibromatosis type II is caused by a pathogenic variant that occurs in the NF2 gene and is inherited in an autosomal dominant manner. This gene plays the role of a tumor suppressor gene that inhibits the occurrence of certain tumors.",
				GeneN040.ALK, GeneN040.EZH2, GeneN040.FH, GeneN040.NF1, GeneN040.NF2, GeneN040.NSD1, GeneN040.PHOX2B, GeneN040.SDHAF2, GeneN040.SDHB);
		private final String title;
		private final String information;
		private final String feature;
		private final Gene[] genes;
		CancerTypeN040(String title, String information, String feature, Gene... genes) {
			this.title = title;
			this.information = information;
			this.feature = feature;
			this.genes = genes;
		}
	}
	@Getter
	@Accessors(fluent = true)
	private enum GeneN040 implements Gene {
		AIP, ALK, APC, ATM, BAP1, BARD1, BLM, BMPR1A, BRCA1, BRCA2, BRIP1, BUB1B, CDC73, CDH1, CDK4, CDKN1C, CDKN2A, CEBPA, CEP57, CHEK2, CYLD, DDB2, DICER1, DIS3L2, EGFR, EPCAM,
		ERCC2, ERCC3, ERCC4, ERCC5, EXT1, EXT2, EZH2, FANCA, FANCB,
		FANCC, FANCD2, FANCE, FANCF, FANCG, FANCI, FANCL, FANCM, FH, FLCN, GATA2, GPC3, HNF1A, HOXB13, HRAS, KIT, MAX, MEN1, MET, MLH1, MSH2, MSH6, MUTYH, NBN, NF1, NF2, NSD1, PALB2, PHOX2B, PMS1,
		PMS2, PPM1D, PRF1, PRKAR1A, PTCH1, PTEN, RAD51C, RAD51D, RB1, RECQL4, RET, RHBDF2, RUNX1, SBDS, SDHAF2, SDHB, SDHC, SDHD, SLX4, SMAD4, SMARCA4, SMARCB1, STK11, SUFU,
		TMEM127, TP53, TSC1, TSC2, VHL, WRN, WT1, XPA, XPC;
		public String symbol() { return name() ;}
	}
	private final String[] references = new String[] {
			"NCCN guidelines (https://www.nccn.org/home)",
			"GeneReviews (https://www.ncbi.nlm.nih.gov/books/NBK1116/)",
			"NIH National cancer institute (https://www.cancer.gov/)",
			"NORD (https://rarediseases.org/)"
	};
}
