# -----------------------
# JPA CONFIGURATION
# -----------------------
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.format_sql=true

# -----------------------
# LIMS POSTGRESQL CONFIGURATION
# -----------------------
spring.datasource.url=jdbc:postgresql://gemini:5432/lims
spring.datasource.username=postgres
spring.datasource.password=snubi1004
spring.datasource.driver-class-name=org.postgresql.Driver

worklist.id=5fd630a8-f9fc-4a17-872a-5b3e82929d6a

# -----------------------
# LIMS Zookeeper CONFIGURATION
# -----------------------
spring.application.name=lagacy-service
spring.cloud.zookeeper.discovery.enabled=true
spring.cloud.zookeeper.discovery.root=/panel-services
spring.cloud.zookeeper.connect-string=test:12181

server.port = 0