# -----------------------
# LIMS POSTGRESQL CONFIGURATION
# -----------------------
spring.datasource.jdbc-url=jdbc:postgresql://gemini:5432/lims
spring.datasource.username=panel
spring.datasource.password=snubi1004
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# -----------------------
# LIMS ELASTICSEARCH CONFIGURATION
# -----------------------
spring.elasticsearch.rest.uris=gemini:9200,pisces:9200
spring.data.elasticsearch.repositories.enabled=true


gcgenome.tmp-dir              = C:\\Affymetrix\\AA
gcgenome.processed-dir          = C:\\Affymetrix\\Pr
gcgenome.undefined-dir          = C:\\Affymetrix\\Er

greencross.webhook.url = https://wh.jandi.com/connect-api/webhook/17558388/67814f3b81e70468e64b72284e9844ca
greencross.webhook.url.cancer = https://wh.jandi.com/connect-api/webhook/17558388/33055b7b65a1bbbb42f36665979dba32
greencross.webhook.url.brca = https://wh.jandi.com/connect-api/webhook/17558388/6da3dafb809e0634b5913b2e123dee2b
greencross.webhook.url.dgs = https://wh.jandi.com/connect-api/webhook/17558388/13e55902e35ff069c7a53f5547e8a8bc